-- INSERT INTO Blacklists VALUES
--  ("user0","user9"), 
--	("user1","user8"), 
--	("user2","user7"), 
--	("user3","user6"), 
--	("user4","user5"), 
--	("user5","user4"), 
--	("user6","user3"), 
--	("user7","user2"), 
--	("user8","user1"),
--	("user9","user0"),
--	("user2","user0");
