package com.mytalk.server.logic.processing;

public abstract class genericRequest {
	
	public genericRequest(){};
	
	public void NotRegisteredCall(){};
	public void RegisteredCall(){};
	public void RefuseCallC(){};
	public void CreateAccount(){};
	public void DeleteAccount(){};
	public void Login(){};
	public void Logout(){};
	public void PasswordRetriver(){};
	public void ConfirmChangePassword(){};
	public void ChangePassword(){};
	public void UpdateEmail(){};
	public void ConfirmUpdateEmail(){};
	public void AccountConfirm(){};
	public void ListCreate(){};
	public void ListDelete(){};
	public void ListUserAdd(){};
	public void ListUserRemove(){};
	public void BlacklistAdd(){};
	public void BlackListRemove(){};
	public void GetCalls(){};
	public void GetGlobalStats(){};
	public void AddCall(){};
	public void UserOffline(){};
	public void RequestCall(){};
	public void AcceptCall(){};
	public void RefuseCallS(){};
	public void SuccessfulCreateAccount(){};
	public void UnsuccessfulCreateAccount(){};
	public void SuccessfulDeleteAccount(){};
	public void SuccessfulLogin(){};
	public void UnsuccessfulLogin(){};
	public void SuccessfulLogout(){};
	public void UnsuccessfulLogout(){};
	public void SuccessfulPasswordRetriever(){};
	public void SuccessfulChangePassword(){};
	public void UnsuccessfulChangePassword(){};
	public void SuccessfulUpdateEmail(){};
	public void SuccessfulConfirmUpdateEmail(){};
	public void SuccessfulAccountConfirm(){};
	public void SuccessfulListCreate(){};
	public void UnsuccessfulListCreate(){};
	public void SuccessfulListDelete(){};
	public void SuccessfulListUserAdd(){};
	public void UnsuccessfulListUserAdd(){};
	public void SuccessfulListUserRemove(){};
	public void UnsuccessfulListUserRemove(){};
	public void SuccessfulBlacklistAdd(){};
	public void UnsuccessfulBlacklistAdd(){};
	public void SuccessfulBlacklistRemove(){};
	public void UnsuccessfulBlacklistRemove(){};
	public void UpdateStatus(){};
	public void GiveGlobalStats(){};
	public void GiveCalls(){};
}
